AnimalsHelp/urls.py
from django.contrib import admin
from django.urls import path

from AnimalsTeam import views

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
]

accounts/urls.py
from django.contrib import admin
from django.urls import path


from accounts import views

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.UserCreationView.as_view(), name='register'),
    path('perm/<int:id>/', views.UserPermissionView.as_view(), name='perm'),

]

AnimalsTeam/models.py
from django.contrib.auth.models import User, AbstractUser
from django.db import models
from django.urls import reverse

# Create your models here.

ROLE = (
    (1, 'adopter'),
    (2, "volunteer"),
)

SPECIES = (
    (1, 'dog'),
    (2, 'cat'),
    (3, 'rabit'),
    (4, 'horse'),
    (5, 'bird'),
    (6, 'goat'),
    (6, 'cow'),
)
HEALTH = (
    (1, "healthy"),
    (2, "chronically sick"),
    (3, "seriously ill"),
    (4, "during treatment"),
    (5, "moribund"),
)

STATUS_ADOPTION = (
    (1, 'waiting for adoption'),
    (2, 'in the middle of trying to adopt'),
    (3, 'not to adoption'),
    (4, 'adopted'),
)

STATUS_ADOPTER = (
    (1, 'in the middle of trying to adopt'),
    (2, 'adopted'),
)

SPECIALIZATION = (
    (1, 'pets permitted'),
    (2, 'exotic pets'),
    (3, 'livestock'),
)

TYPE_OF_FOOD = (
    (1, "emergency animal feed"),
    (2, "animal feed")
)


class Animals(models.Model):
    name = models.CharField(max_length=60, unique=True)
    species = models.IntegerField(choices=SPECIES)
    health = models.IntegerField(choices=HEALTH)
    status = models.IntegerField(choices=STATUS_ADOPTION)

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse('animal_detail_view', args=(self.pk,))


class Personel(models.Model):
    name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=120)
    role = models.IntegerField(choices=ROLE)
    join_date = models.DateTimeField(blank=False)
    description = models.CharField(max_length=500)
    animals = models.ManyToManyField(Animals, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}{self.last_name}'

    def get_absolute_url(self):
        return reverse('personel_detail_view', args=(self.pk,))

    def get_absolute_url1(self):
        return reverse('adopter_detail_view', args=(self.pk,))


# class Adopter(models.Model):
#     name = models.CharField(max_length=60)
#     last_name = models.CharField(max_length=120)
#     address = models.CharField(max_length=120)
#     animal = models.ManyToManyField(Animals, blank=True)
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#
#     def __str__(self):
#         return f'{self.name} {self.last_name}'
#
#     def get_absolute_url(self):
#         return reverse('adopter_detail_view', args=(self.pk,))

class Adoption(models.Model):
    animal = models.ForeignKey(Animals, on_delete=models.CASCADE)
    adopter = models.ForeignKey(Personel, on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUS_ADOPTER)


class Vet(models.Model):
    name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=120)
    specialization = models.IntegerField(choices=SPECIALIZATION)
    animals = models.ManyToManyField(Animals, blank=True)

    def __str__(self):
        return f"{self.name} {self.last_name}"

    def get_absolute_url(self):
        return reverse('vet_detail_view', args=(self.pk,))


class Food(models.Model):
    name = models.CharField(max_length=60)
    type = models.IntegerField(choices=TYPE_OF_FOOD)
    stan = models.IntegerField()

    def __str__(self):
        return f"{self.stan} {self.name} {self.type}"

    def get_absolute_url(self):
        return reverse('food_detail_view', args=(self.pk,))

templates/adopter_detail_view.html
{% extends 'base.html' %}
{% block content %}

    <h1>{{ object.name }} {{ object.last_name }} </h1>
    <p>{{ object.description }}</p>

{% endblock content %}

templates/adoption_delete_view.html
<form method="post">
    {% csrf_token %}
    Are you sure that you want to delete?
    <input type="submit" value="Yes">
</form>

templates/adoption_list.html
{% extends 'base.html' %}
{% block title %}Adopcje {% endblock title %}
{% block content %}
    <h1>Adoption</h1>
    <ul>
        {% for obj in adoption_list %}
            <li><h3>{{ obj.animal }}</h3> adopted to <b>{{ obj.adopter }}</b> status adoption
                <b>{{ obj.get_status_display }}</b></li>
            {% if perms.AnimalTeam.delete_adoption %}
                <a href="{% url 'delete_adoption' obj.id %}"><input type="submit" value="Delete"></a>
            {% endif %}
        {% endfor obj %}

    </ul>
{% endblock content %}

templates/animal_detail_view.html
{% extends 'base.html' %}
{% block title %}{{ object.name }}{% endblock title %}
{% block content %}
    <h1>{{ object.name }}</h1>
    <h2>{{ object.get_species_display}}</h2>
    <h3>{{ object.get_health_display}}</h3>
    <h3>{{ object.get_status_display}}</h3>
{#    <input type="submit" value="Edytuj">#}
{#    <input type="submit" value="Usuń">#}
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    <title>AnimalsHelp</title>
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
<div class="topnav">
    <a class="active" href="{% url 'index' %}">Home</a>

    <a href="{% url 'all_animals' %}">Our Animals</a>
    <a href="{% url 'add_animals' %}">Add Animal</a>


    <a href="{% url 'about_volunteers' %}">Volunteers</a>
    <a href="{% url 'add_volunteers' %}">Sing up for volunteering</a>

    <a href="{% url 'adopter_list' %}">Adopters</a>
    <a href="{% url 'add_adopter' %}">Sing up for adoption</a>
    <a href="{% url 'adoption_list' %}">Found a new House</a>
    {% if perms.AnimalTeam.add_adoption %}
        <a href="{% url 'add_adoption' %}">Adoption</a>
    {% endif %}

    <a href="{% url 'all_vet' %}">Our Vets</a>
    {% if perms.AnimalTeam.add_vet %}
        <a href="{% url 'add_vet_view' %}">Add Vet</a>
    {% endif %}
    <a href="{% url 'food' %}">Our Supply</a>
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'register' %}">Register</a>
    {% endif %}
    <a href="{% url 'contact' %}">Contact</a>
</div>
{{ user }}
<div class="contener">
    {% block content %} {% endblock content %}
</div>

</body>
</html>

templates/book_delete_view.html
{% extends 'base.html' %}
{% block content %}
    <p>{{ object.pk }}</p>
    <p>{{ object.name }}</p>
    <p>{{ object.last_name }}</p>

{% endblock content %}

templates/contact.html
{% extends 'base.html' %}
{% block content %}
<h1>Contant</h1>
    <h2>Animal Help</h2>
    <h3>ul.Mirusia 34, 99-000 Zabrze</h3>
    <p>email: animalhelm@gmail.com</p>
    <p>phone number: 510-111-222</p>

{% endblock content %}

templates/food_edit.html
{% extends 'base.html'%}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock content %}

templates/food_list.html
{% extends 'base.html' %}
{% block title %}Karma{% endblock title %}
{% block content %}
    <h1>Our Food Supplies</h1>

    {% for obj in food_list %}
   <li> <a href="{{ obj.get_absolute_url }}">{{obj.name}}</a>--{{ obj.stan }} kg -- {{ obj.get_type_display }}  </li>
    {% endfor obj %}
    <a href="{% url 'add_food' %}"><input type="submit" value="Add feed"></a>
{% endblock content %}

templates/form.html
{% extends 'base.html' %}
{% block title %}Formularz dodawania{% endblock title %}
{% block content %}
    <form method="post" class="form_class">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add">
    </form>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% block content %}

<p>"If you want to be great, just help."</p>
<p>We are a non-profit organization. We help the animal to recover and to lay a new home. </p>
<p>Do you want to help? Sign up for volunteering. It's the greatest job in the world.</p>
<p>Want to give a new home? Sign up for adoption.</p>
<p>If you want to support us otherwise, you may bring the humiliating information to the address you provided in
    contact:</p>
<li>emergency animal feed</li>
<li>hay</li>
<li>blankets</li>
<li>blankets</li>
<li>pens for animals</li>
<li>towels, leashes, bowls, toys</li>

{% endblock content %}

templates/list_view.html
<ul>
    {% for obj in objects_list %}
        <li><a href="{{ obj.get_absolute_url }}">{{ obj }}</a></li>
    {% endfor obj %}
</ul>

templates/personel_detail_view.html
{% extends 'base.html' %}
{% block title %}{{ object.name }} {{ object.last_name }}{% endblock title %}
{% block content %}
    <h1>{{ object.name }} {{ object.last_name }}</h1>
    <h3>Data dołączenia:</h3>
    <h2>{{ object.join_date}}</h2>
    <h3>O mnie:</h3>
    <p>{{ object.description}}</p>
{% endblock content %}

templates/vet_detail.html
{% extends 'base.html' %}
{% block title %}{{ object.name }}{{ object.last_name }}{% endblock title %}
{% block content %}
    <h1>{{ object.name }}</h1>
    <h1>{{ object.last_name }}</h1>
    <h2>{{ object.get_specialization_display}}</h2>
    {% if perms.AnimalTeam.add_vet %}
    <a href="{% url 'vet_delete_view' object.id %}"><input type="submit" value="Delete"></a>
    {% endif %}
{% endblock content %}